version: '3.3'
services:
    db:
        image: mysql:latest
        container_name: mysql
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-buffer-pool-size=2G  --innodb-buffer-pool-size=2G
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: onisep
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-pexample"
                ]
            interval: 45s
            timeout: 75s
            retries: 2
    phpmyadmin:
        image: phpmyadmin
        container_name: Onisep_phpmyadmin

        ports:
            - 8484:80
        depends_on:
            - db
    api:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: db
        container_name: Onisep_REST_API
        restart: always
        ports:
            - 5005:5005
        depends_on:
            db:
                condition: service_healthy
volumes:
    db:
