version: '3.3'
services:
    db:
        image: mariadb:10.5
        container_name: mariadb
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-buffer-pool-size=2G
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: onisep
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-pexample"
                ]
            interval: 45s
            timeout: 75s
            retries: 2
    phpmyadmin:
        image: phpmyadmin
        restart: always
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRATY=1
        ports:
            - 8484:80
        depends_on:
            - db
    api:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: db
        container_name: api
        restart: always
        ports:
            - 5005:5005
        depends_on:
            db:
                condition: service_healthy
volumes:
    db:
