version: '3.3'
services:
    db:
        image: mariadb:latest
        container_name: Onisep_mysql;
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_DATABASE=onisep
            - MYSQL_USER=${DATABASE_USERNAME}
    phpmyadmin:
        image: phpmyadmin
        container_name: Onisep_phpmyadmin
        environment:
            - PMA_ARBITRATY=1
        ports:
            - 8484:80
        links:
            - db
    api:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - DATABASE_USERNAME:${DATABASE_USERNAME}
            - DATABASE_PASSWORD:${DATABASE_PASSWORD}
            - DATABASE_HOST:db
        container_name: Onisep_REST_API
        restart: always
        ports:
            - 5005:5000
        depends_on:
            - db
volumes:
    db:
