version: '3.3'
services:
    db:
        image: mariadb:latest
        container_name: Onisep_mysql
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-buffer-pool-size=2G
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=onisep
            - MARIADB_USER=${DATABASE_USERNAME}
            - MARIADB_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        container_name: Onisep_phpmyadmin
        environment:
            - PMA_ARBITRATY=1
        restart: always
        ports:
            - 8484:80
        links:
            - db
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: onisep_api:latest
        container_name: Onisep_REST_API
        environment:
            - SECRET_KEY=siueubn
            - DATABASE_USERNAME:${DATABASE_USERNAME}
            - DATABASE_PASSWORD:${DATABASE_PASSWORD}
            - DATABASE_HOST:db
        restart: always
        ports:
            - 5005:5005
        depends_on:
            - db
volumes:
    db:
