version: '3.3'
services:
    api:
        image: onisepapi:v1.0.21
        environment:
            - SECRET_KEY=mysecretkey
            - FLASK_ENV=development
            - SQLALCHEMY_DB_URI=sqlite:///onisepapi.db
        container_name: Onisep_API1
        restart: always
        ports:
            - 5005:5000
