version: '3.3'
services:
    db:
        image: mariadb:latest
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_PASSWORD=
            - MYSQL_DATABASE=onisep
            - MYSQL_USER=Onisep_Admin
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRATY=1
        ports:
            - 8484:80
        links:
            - db
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: onisepapi
        environment:
            - SECRET_KEY=
            - SQLALCHEMY_DB_URI=
        container_name: Onisep_API1
        restart: always
        ports:
            - 5005:5000
        depends_on:
            - db
volumes:
    db:
