"""Update size for 'demain' again.

Revision ID: 1932d4fa450b
Revises: 3d2e4be5a52b
Create Date: 2023-10-31 01:10:05.699656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1932d4fa450b"
down_revision = "3d2e4be5a52b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "formation",
        "domain",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "formation",
        "domain",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
