"""Alter table formation upate size.

Revision ID: 3d2e4be5a52b
Revises: ee56a7eaab4a
Create Date: 2023-10-31 00:49:13.312551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3d2e4be5a52b"
down_revision = "ee56a7eaab4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "formation",
        "type",
        existing_type=mysql.VARCHAR(length=120),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "formation",
        "libelle",
        existing_type=mysql.VARCHAR(length=120),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "formation",
        "tutelle",
        existing_type=mysql.VARCHAR(length=120),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "formation",
        "niveau_de_sortie",
        existing_type=mysql.VARCHAR(length=120),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "formation",
        "duree",
        existing_type=mysql.VARCHAR(length=15),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_constraint("favori_formation_id_fk", "user_favori", type_="foreignkey")
    op.create_foreign_key(
        None, "user_favori", "formation", ["formation_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_favori", type_="foreignkey")
    op.create_foreign_key(
        "favori_formation_id_fk", "user_favori", "formation", ["formation_id"], ["id"]
    )
    op.alter_column(
        "formation",
        "duree",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "formation",
        "niveau_de_sortie",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=120),
        existing_nullable=False,
    )
    op.alter_column(
        "formation",
        "tutelle",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=120),
        existing_nullable=False,
    )
    op.alter_column(
        "formation",
        "libelle",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=120),
        existing_nullable=False,
    )
    op.alter_column(
        "formation",
        "type",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=120),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
