"""empty message

Revision ID: 47c4e50f11de
Revises: 
Create Date: 2023-04-30 19:49:07.901489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47c4e50f11de"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("pdp_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "favori",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code_nsf", sa.Text(), nullable=True),
        sa.Column("sigle_type_formation", sa.Text(), nullable=True),
        sa.Column("libelle_type_formation", sa.Text(), nullable=True),
        sa.Column("libelle_formation_principal", sa.Text(), nullable=True),
        sa.Column("sigle_formation", sa.Text(), nullable=True),
        sa.Column("duree", sa.Text(), nullable=True),
        sa.Column("niveau_de_sortie_indicatif", sa.Text(), nullable=True),
        sa.Column("code_rncp", sa.Text(), nullable=True),
        sa.Column("niveau_de_certification", sa.Text(), nullable=True),
        sa.Column("libelle_niveau_de_certification", sa.Text(), nullable=True),
        sa.Column("tutelle", sa.Text(), nullable=True),
        sa.Column("url_et_id_onisep", sa.Text(), nullable=False),
        sa.Column("request_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favori")
    op.drop_table("user")
    # ### end Alembic commands ###
