"""empty message

Revision ID: 8ce7337ffbf4
Revises: 47c4e50f11de
Create Date: 2023-06-30 11:47:16.940598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8ce7337ffbf4"
down_revision = "47c4e50f11de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("profile_pic_url", sa.Text(), nullable=True))
    op.drop_column("user", "pdp_url")
    op.drop_column("user", "name")
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE user SET created_at = now()")
    op.execute("UPDATE user SET updated_at = now()")
    op.alter_column("user", "created_at", existing_type=sa.DateTime(), nullable=False)
    op.alter_column("user", "updated_at", existing_type=sa.DateTime(), nullable=False)

    op.add_column("favori", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("favori", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE favori SET created_at = now()")
    op.execute("UPDATE favori SET updated_at = now()")
    op.alter_column("favori", "created_at", existing_type=sa.DateTime(), nullable=False)
    op.alter_column("favori", "updated_at", existing_type=sa.DateTime(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", mysql.VARCHAR(length=200), nullable=False))
    op.add_column("user", sa.Column("pdp_url", mysql.TEXT(), nullable=True))
    op.drop_column("user", "profile_pic_url")
    # ### end Alembic commands ###
