"""Create formation table

Revision ID: a3fe3092f50c
Revises: 8ce7337ffbf4
Create Date: 2023-10-29 15:59:03.950861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3fe3092f50c"
down_revision = "8ce7337ffbf4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "formation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code_nsf", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=120), nullable=False),
        sa.Column("libelle", sa.String(length=120), nullable=False),
        sa.Column("tutelle", sa.String(length=120), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("niveau_de_sortie", sa.String(length=120), nullable=False),
        sa.Column("duree", sa.String(length=15), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("formation")
    # ### end Alembic commands ###
